AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: hello-world/hello-world.handler
      Runtime: nodejs20.x
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  HelloWorldUrl:
    Value: !GetAtt HelloWorldLambdaUrl.FunctionUrl
