name: Main Pipeline
on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install
        run: npm ci

      - name: format
        run: npm run check-format

      - name: test
        run: npm run test
